{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "monero-kit-android",
    "version": "0838cef",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-0838cef.aar",
          "url": "monero-kit-android-0838cef.aar",
          "size": 43833509,
          "sha512": "f128ecece4ebdabcdf1c4e6afa9a961f9f2a65ebe136f5fa620cdf137aecd29d5d678cfe7a5e962980f42b0c4d5d89f22a7463c994bbe2ec35fb76ac4c48dd7a",
          "sha256": "7cf0aab1608b3d73a0cc0e4530cfa39f799bca84e84424848148a426604877f5",
          "sha1": "474d2debc0aa06e1eb44b2f9daaaa0721f94c057",
          "md5": "cf8122b3d0582565517a922c72e24346"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "io.github.rburgst",
          "module": "okhttp-digest",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-0838cef.aar",
          "url": "monero-kit-android-0838cef.aar",
          "size": 43833509,
          "sha512": "f128ecece4ebdabcdf1c4e6afa9a961f9f2a65ebe136f5fa620cdf137aecd29d5d678cfe7a5e962980f42b0c4d5d89f22a7463c994bbe2ec35fb76ac4c48dd7a",
          "sha256": "7cf0aab1608b3d73a0cc0e4530cfa39f799bca84e84424848148a426604877f5",
          "sha1": "474d2debc0aa06e1eb44b2f9daaaa0721f94c057",
          "md5": "cf8122b3d0582565517a922c72e24346"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "monero-kit-android-0838cef-sources.jar",
          "url": "monero-kit-android-0838cef-sources.jar",
          "size": 389161,
          "sha512": "1064b9037e2374979b4469c2a9177530debf7b66877c9a73a19972f4afe18a41b7e75e9c913b4d30a156f383b613af9107f4e9d9c4ead4eabf0da5609f56a79b",
          "sha256": "fe8d2341928672da416678db6f8301f0c885c35e04a6ebfb6d2d758a7f03d575",
          "sha1": "3c36cb71e157e4111f56f42c2e08707e7edb1044",
          "md5": "4bd5d9f4ffb22deffe206d734b41d044"
        }
      ]
    }
  ]
}
