{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "monero-kit-android",
    "version": "93ef0e6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-93ef0e6.aar",
          "url": "monero-kit-android-93ef0e6.aar",
          "size": 27614267,
          "sha512": "c2f704317dae8a4dd6cb94de1af7afab47852b8a902a0e4073897e57f83a8800f1d4f94198c2b9d4979fec9c01301540c595fa2ceee5cfd78fcf34cfdb03a269",
          "sha256": "487fcad79e7b3e09b3356dfadcd60c88b51bb9f76c747fe1147c491f23424124",
          "sha1": "1c71fb46cdcc31a1ad5307f1a6ec1581418b0c1f",
          "md5": "eb37788c64a4e86a197d4d38d47ff749"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.rburgst",
          "module": "okhttp-digest",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-93ef0e6.aar",
          "url": "monero-kit-android-93ef0e6.aar",
          "size": 27614267,
          "sha512": "c2f704317dae8a4dd6cb94de1af7afab47852b8a902a0e4073897e57f83a8800f1d4f94198c2b9d4979fec9c01301540c595fa2ceee5cfd78fcf34cfdb03a269",
          "sha256": "487fcad79e7b3e09b3356dfadcd60c88b51bb9f76c747fe1147c491f23424124",
          "sha1": "1c71fb46cdcc31a1ad5307f1a6ec1581418b0c1f",
          "md5": "eb37788c64a4e86a197d4d38d47ff749"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "monero-kit-android-93ef0e6-sources.jar",
          "url": "monero-kit-android-93ef0e6-sources.jar",
          "size": 333926,
          "sha512": "7f5706acbdb85021c64f16189dd20c81745dfb3640fb4cc31123b4aed5b53d4c9cb43180909732885287a9eff1d80f9241d2ecf48c69cd31b82a4b81cf513190",
          "sha256": "66bebea369daab84fb0e27d26e967bad572f9139197858f00f2978a7152becab",
          "sha1": "38e7e74e1b6ad91a8a51ff81510d3c2089b80795",
          "md5": "e540c453270231ab82e366bbacebccba"
        }
      ]
    }
  ]
}
