{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "monero-kit-android",
    "version": "7c7d3f6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-7c7d3f6.aar",
          "url": "monero-kit-android-7c7d3f6.aar",
          "size": 27617858,
          "sha512": "b1bd72ef509869f4ed9ed5b1731da1398e3d4e3f37a12690dc5f9bb7e0ad9d75b15a23bc23c238428bc62754769265defc6180c2260499d75d034f08da4b3bd9",
          "sha256": "0adbb61c682eeceed812396b255b2583c5e2b980648f13724741e92b8bb10bc3",
          "sha1": "ac65d848f3a878452cc93bc3f6ebf2373785645d",
          "md5": "921e6cec6d1cae744c0fd8f2c8fee368"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.rburgst",
          "module": "okhttp-digest",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-7c7d3f6.aar",
          "url": "monero-kit-android-7c7d3f6.aar",
          "size": 27617858,
          "sha512": "b1bd72ef509869f4ed9ed5b1731da1398e3d4e3f37a12690dc5f9bb7e0ad9d75b15a23bc23c238428bc62754769265defc6180c2260499d75d034f08da4b3bd9",
          "sha256": "0adbb61c682eeceed812396b255b2583c5e2b980648f13724741e92b8bb10bc3",
          "sha1": "ac65d848f3a878452cc93bc3f6ebf2373785645d",
          "md5": "921e6cec6d1cae744c0fd8f2c8fee368"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "monero-kit-android-7c7d3f6-sources.jar",
          "url": "monero-kit-android-7c7d3f6-sources.jar",
          "size": 333926,
          "sha512": "7f5706acbdb85021c64f16189dd20c81745dfb3640fb4cc31123b4aed5b53d4c9cb43180909732885287a9eff1d80f9241d2ecf48c69cd31b82a4b81cf513190",
          "sha256": "66bebea369daab84fb0e27d26e967bad572f9139197858f00f2978a7152becab",
          "sha1": "38e7e74e1b6ad91a8a51ff81510d3c2089b80795",
          "md5": "e540c453270231ab82e366bbacebccba"
        }
      ]
    }
  ]
}
