{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.piratecash",
    "module": "monero-kit-android",
    "version": "a6663ed",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-a6663ed.aar",
          "url": "monero-kit-android-a6663ed.aar",
          "size": 27628395,
          "sha512": "0496db4e07ca77763bc9e158ce1c286aa1c408e7def27b946eb3f871e76a6cb6a5dc27333f9a17d5f9633fe0bbd9ad9eef422e464d974c407d45c979d309cb53",
          "sha256": "1de499f9f2db6b4d1436b875fb27b22a482d295889a5c54b3b72f0c63c14595a",
          "sha1": "d6278791c7cbf5f321cadffad7466532b1be17ff",
          "md5": "7479285189fd589f8e1ffb046c97d1d0"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "com.jakewharton.timber",
          "module": "timber",
          "version": {
            "requires": "5.0.1"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.4.8-android"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "io.github.rburgst",
          "module": "okhttp-digest",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "info.guardianproject.netcipher",
          "module": "netcipher",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "monero-kit-android-a6663ed.aar",
          "url": "monero-kit-android-a6663ed.aar",
          "size": 27628395,
          "sha512": "0496db4e07ca77763bc9e158ce1c286aa1c408e7def27b946eb3f871e76a6cb6a5dc27333f9a17d5f9633fe0bbd9ad9eef422e464d974c407d45c979d309cb53",
          "sha256": "1de499f9f2db6b4d1436b875fb27b22a482d295889a5c54b3b72f0c63c14595a",
          "sha1": "d6278791c7cbf5f321cadffad7466532b1be17ff",
          "md5": "7479285189fd589f8e1ffb046c97d1d0"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "monero-kit-android-a6663ed-sources.jar",
          "url": "monero-kit-android-a6663ed-sources.jar",
          "size": 333926,
          "sha512": "7f5706acbdb85021c64f16189dd20c81745dfb3640fb4cc31123b4aed5b53d4c9cb43180909732885287a9eff1d80f9241d2ecf48c69cd31b82a4b81cf513190",
          "sha256": "66bebea369daab84fb0e27d26e967bad572f9139197858f00f2978a7152becab",
          "sha1": "38e7e74e1b6ad91a8a51ff81510d3c2089b80795",
          "md5": "e540c453270231ab82e366bbacebccba"
        }
      ]
    }
  ]
}
